### ISSUE TITLE
Glitches on DAC output

### ISSUE THREAD

**Issue by wilsonjwcsu** [eefer/DE2-115_DualLockins#1]
![image](https://user-images.githubusercontent.com/16198875/28629607-28294b14-71e5-11e7-8d5f-87a526c65e13.png)
I had one lockin set to a particular frequency and the other just set to a frequency of zero. The signal from the DAC is a sinusoid with the expected frequency but it has what I would call noise spikes in it (see below). They always occur at the same points in the curve and about every 1 out of 3 cycles.
(Problem observed by Erin and Jason 7/25/2017)

**Comment by wilsonjwcsu** [comment]
The oscilloscope pic you sent looks like symptoms of a timing problem. Arya has a barebones project with just the nco that we should test,  looking carefully for those glitches. Either it's a problem with the nco, or with something that relays the nco signal through to the DAC.

**Comment by eefer** [comment]
I no longer have glitches on my DAC output or ADC input as viewed from SignalTap. No glitches on the output from the DAC when viewed on an oscope. I will still work on updating the timing constraints though.
