### ISSUE TITLE
SignalTap failure after git pull and recompile

### ISSUE THREAD

**Issue by wilsonjwcsu** [eefer/DE2-115_DualLockins#2]
(from Erin-- see email below)

Hi Jesse,

Whenever there are differences in the compiled versions between me and Arya, I get this strange behavior that when I compile, then afterward SignalTap will only show 2 data points of every signal. It happened again today. I've been able to fix this problem in the past by finding the conflict or by erasing all my files and downloading the most recent version from GitHub. I am working on how to fix this issue today.

I am wondering how we can avoid this kind of conflict in the future. Which files should we be pushing to GitHub and which should we not? What would be the best way to deal with Quartus file conflicts?

Erin

**Comment by wilsonjwcsu** [comment]
There are a lot of temporary files committed to the repository. I think that once we add those to the git ignore list, a lot of these problems might go away. 

This is something we need to look into more. Here are a few places to start:
http://justacodestory.blogspot.com/2013/06/how-to-store-quartus-project-in-vcs-on.html
https://www.reddit.com/r/FPGA/comments/1fnosm/does_anyone_use_git_with_fpga_projects/

**Comment by wilsonjwcsu** [comment]
One more thought—which files, specifically, have been producing the conflicts?

**Comment by wilsonjwcsu** [comment]
In DE2-115 ADC_DAC\a2dv2, I've deleted the major temp file directories and added them to the ignore list (db, greybox_tmp, and incremental_db). Let's see if that helps, then start looking at other files in a2dv2 that are temporarily generated by quartus when it compiles.

**Comment by eefer** [comment]
This did seem to work. I was able to run the latest version on commit and also compile it without the SignalTap outputs being removed.

**Comment by wilsonjwcsu** [comment]
OK, then I'll close this issue for now. We can reopen it if it becomes a problem later.
